### ISSUE TITLE
Bug with fully observable small enviroments

### ISSUE THREAD

**Issue by NixGD** [lcswillems/rl-starter-files#27]
The size of the observation space of mini-gridworlds now depends on the size of the environment for fully observational spaces instead of always being (7,7,3).  This causes errors for environments which have a dimension of 6 or smaller due to this line: https://github.com/lcswillems/rl-starter-files/blob/e37dd17f9115c08b4234cc85b38f7429c9623560/model.py#L36 since the embedding size is set to zero.  This results in a division by zero error:

```Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nix/cirl/scripts/train.py", line 121, in <module>
    acmodel = ACModel(obs_space, envs[0].action_space, args.mem, args.text)
  File "/Users/nix/cirl/model.py", line 63, in __init__
    nn.Linear(self.embedding_size, 64),
  File "/Users/nix/cirl/env/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 56, in __init__
    self.reset_parameters()
  File "/Users/nix/cirl/env/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 59, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/Users/nix/cirl/env/lib/python3.7/site-packages/torch/nn/init.py", line 291, in kaiming_uniform_
    std = gain / math.sqrt(fan)
ZeroDivisionError: float division by zero
```

**Comment by lcswillems** [comment]
Hi,

Minigrid or miniworld?
Can you give me a precise observation space shape?
Is this error new?

**Comment by lcswillems** [comment]
Hi,
I close your issue because of lack of details. Don't hesitate to open it again with the additional details.
