### ISSUE TITLE
Training broken on MiniGrid envs?

### ISSUE THREAD

**Issue by maximecb** [lcswillems/rl-starter-files#28]
With the latest clone of this repo, installing from requirements.txt:

```
python3 -m scripts.train --algo ppo --env MiniGrid-DoorKey-5x5-v0 --save-interval 10 --frames 8000000

Namespace(algo='ppo', batch_size=256, clip_eps=0.2, discount=0.99, entropy_coef=0.01, env='MiniGrid-DoorKey-5x5-v0', epochs=4, frames=8000000, frames_per_proc=None, gae_lambda=0.95, log_interval=1, lr=0.0007, max_grad_norm=0.5, mem=False, model=None, optim_alpha=0.99, optim_eps=1e-05, procs=16, recurrence=1, save_interval=10, seed=1, tb=False, text=False, value_loss_coef=0.5)

Traceback (most recent call last):
  File "/home/maximecb/Desktop/rl-starter-files/scripts/train.py", line 117, in <module>
    acmodel = utils.load_model(model_dir)
  File "/home/maximecb/Desktop/rl-starter-files/utils/save.py", line 15, in load_model
    model = torch.load(path)
  File "/home/maximecb/.local/lib/python3.6/site-packages/torch/serialization.py", line 366, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'storage/MiniGrid-DoorKey-5x5-v0_ppo_seed1_19-04-30-15-38-46/model.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maximecb/Desktop/rl-starter-files/scripts/train.py", line 120, in <module>
    acmodel = ACModel(obs_space, envs[0].action_space, args.mem, args.text)
  File "/home/maximecb/Desktop/rl-starter-files/model.py", line 58, in __init__
    nn.Linear(self.embedding_size, 64),
  File "/home/maximecb/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 56, in __init__
    self.reset_parameters()
  File "/home/maximecb/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 59, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/maximecb/.local/lib/python3.6/site-packages/torch/nn/init.py", line 290, in kaiming_uniform_
    std = gain / math.sqrt(fan)
ZeroDivisionError: float division by zero
```

**Comment by maximecb** [comment]
My bad. Problem was on my end!
