### ISSUE TITLE
Cannot run the scripts 

### ISSUE THREAD

**Issue by goelshivam1210** [lcswillems/rl-starter-files#39]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/env1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/env1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/../rl_in_polycraft_domain/base_environment/rl-starter-files/scripts/train.py", line 5, in <module>
    import torch_ac
ModuleNotFoundError: No module named 'torch_ac'

I have installed torch-ac as mentioned in the repository. Still, it throws this error. I will appreciate any help.

**Comment by lcswillems** [comment]
This is strange... I don't think the issue is coming from the lib. If `torch-ac` is installed, you should not have this error.

If you provide a repro, I may help.

**Comment by goelshivam1210** [comment]
Hi @lcswillems, I got it to work. I had to manually run the setup.py install in both the directories, namely, gym-minigrid and torch-ac, and now it loads and works. Thanks!
