### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_mm

### ISSUE THREAD

**Issue by Ac31415** [lcswillems/rl-starter-files#46]
Whenever I try to use the visualize script on memory dependent environments and agents, I get the following error:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wen-chung/rl-starter-files/scripts/visualize.py", line 75, in <module>
    action = agent.get_action(obs)
  File "/home/wen-chung/rl-starter-files/utils/agent.py", line 48, in get_action
    return self.get_actions([obs])[0]
  File "/home/wen-chung/rl-starter-files/utils/agent.py", line 36, in get_actions
    dist, _, self.memories = self.acmodel(preprocessed_obss, self.memories)
  File "/home/wen-chung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wen-chung/rl-starter-files/model.py", line 88, in forward
    hidden = self.memory_rnn(x, hidden)
  File "/home/wen-chung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wen-chung/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 955, in forward
    self.bias_ih, self.bias_hh,
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_mm

Here is the command I'm running to reproduce the above error: 
`python3 -m scripts.visualize --env MiniGrid-Empty-RandomGoal-16x16-v0 --model A2CMiniGrid-Empty-RandomGoal-16x16-v0-Int1-Fr10M-LSTM4-Test --memory` 

How do I resolve this issue?

Thanks,
Andy Cheng

**Comment by vitusya** [comment]
@Ac31415 https://github.com/lcswillems/rl-starter-files/pull/47
