### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Shambalak** [lcswillems/rl-starter-files#69]
Hi,
I get an error after executing "!python3 -m scripts.train --algo ppo --env MiniGrid-DoorKey-5x5-v0 --model DoorKey --save-interval 10 --frames 80000".

**Error:**
Optimizer loaded

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/TFM/code/rl-starter-files/scripts/train.py", line 155, in <module>
    exps, logs1 = algo.collect_experiences()
  File "/usr/local/lib/python3.7/dist-packages/torch_ac/algos/base.py", line 129, in collect_experiences
    preprocessed_obs = self.preprocess_obss(self.obs, device=self.device)
  File "/content/drive/MyDrive/TFM/code/rl-starter-files/utils/format.py", line 30, in preprocess_obss
    "image": preprocess_images([obs["image"] for obs in obss], device=device),
  File "/content/drive/MyDrive/TFM/code/rl-starter-files/utils/format.py", line 30, in <listcomp>
    "image": preprocess_images([obs["image"] for obs in obss], device=device),
TypeError: tuple indices must be integers or slices, not str

**Comment by Shambalak** [comment]
Yep, there's a closed issue with the same error. It was the gym version. I have reinstalled gym_minigrid==1.1.0 and it works.
